services:
  server:
    build:
      dockerfile: Dockerfile
      target: development
      context: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: "npm run start:dev"
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ryanairdb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data/ryanairdb/mongo:/data/db
